apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: safe-volume
          mountPath: /data
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
  volumes:
    - name: safe-volume
      emptyDir: {}
